### ISSUE TITLE
add more commands

### ISSUE THREAD

**Issue by Cheezy096** [asexyalt/bot.peepee#1]
Your bot can be usefull towards people that want to begin learning coding bots with discord.py but you need to add more commands with notes

**Comment by asexyalt** [comment]
no

**Comment by Cheezy096** [comment]
use the code of my bot cheese.py to help you with cogs and a config.json file please, do you even know python?

**Comment by asexyalt** [comment]
yes and please don't close the issue

**Comment by Cheezy096** [comment]
but this isn't an issue anymore

**Comment by asexyalt** [comment]
i don't care this is my bot i can do what i like with it fuck off
